# Generated by Django 5.2.1 on 2025-05-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcriberapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcription",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("pl", "Polski"),
                    ("de", "Deutsch"),
                    ("fr", "Français"),
                    ("es", "Español"),
                ],
                max_length=10,
            ),
        ),
    ]
