# Generated by Django 5.2.1 on 2025-05-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcriberapp", "0003_transcription_thumbnail_transcription_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
