# Generated by Django 5.2.1 on 2025-05-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transcriberapp",
            "0004_transcription_duration_alter_transcription_summary_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="asynctask",
            name="done",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
