# Generated by Django 5.2.1 on 2025-05-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transcriberapp", "0005_asynctask_done"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asynctask",
            name="done",
        ),
    ]
